version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 1024M      
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
    environment:
      AUTOPAUSE_TIMEOUT_EST: "600"
      # ENABLE_AUTOPAUSE: "true"
      ENABLE_ROLLING_LOGS: "false"
      EULA: "true"
      VERSION: "1.19.3"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "3G"
      TYPE: "FORGE"
      TZ: "America/Los_Angeles"
      # USE_AIKAR_FLAGS: "true"
      #server.properties settings below this line
      ALLOW_FLIGHT: "false"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      BROADCAST_CONSOLE_TO_OPS: "true"
      BROADCAST_RCON_TO_OPS: "false"
      DIFFICULTY: "normal"
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_JMX: "false"
      ENABLE_QUERY: "false"
      ENABLE_RCON: "true"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      FORCE_GAMEMODE: "false"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      LEVEL_TYPE: "DEFAULT"
      MAX_BUILD_HEIGHT: "256"
      MAX_TICK_TIME: "-1"
      MAX_PLAYERS: "50"
      MODE: "survival"
      MOTD: "Forge Minecraft"
      OPS: "greggawatt,tripleblade1234"
      OP_PERMISSION_LEVEL: "4"
      OVERRIDE_SERVER_PROPERTIES: "true"
      PVP: "false"
      PLAYER_IDLE_TIMEOUT: "0"
      RCON_PASSWORD: "octopus12"
      RCON_PORT: "25575"
      SEED: ""
      SERVER_NAME: "A Forge Minecraft Server"
      SNOOPER_ENABLED: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "10"      
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - type: volume
      source: mc_vol
      target: /data
      read_only: false
    - type: bind
      source: ${HOME}/minecraft/mods
      target: /mods
      read_only: true  
  backupshourly:
    image: itzg/mc-backup
    environment:
      TZ: "America/Los_Angeles"    
      INITIAL_DELAY: "15m"
      RCON_RETRIES: "-1"
      RCON_RETRY_INTERVAL: "15m"
      BACKUP_INTERVAL: "1h"
      PRUNE_BACKUPS_DAYS: "21"
      RCON_PASSWORD: "octopus12"
      RCON_PORT: "25575"
      BACKUP_NAME: "forge"
      EXCLUDES: "*.jar,logs,libraries,cache"
      PAUSE_IF_NO_PLAYERS: "true"
      PLAYERS_ONLINE_CHECK_INTERVAL: "15m"      
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - type: volume
      source: mc_vol
      target: /data
      read_only: true
    - type: bind
      source: ${HOME}/minecraft/backups
      target: /backups
      read_only: false
    network_mode: "service:mc"
volumes:
   mc_vol: {}

